# Generated by Django 2.2 on 2022-03-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='game1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.CharField(max_length=200)),
                ('plural_noun', models.CharField(max_length=200)),
                ('verb', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('celebrity_name', models.CharField(max_length=200)),
            ],
        ),
    ]
