# Generated by Django 2.2 on 2022-03-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_game1'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(max_length=200)),
                ('month', models.CharField(max_length=200)),
                ('adjectiveTwo', models.CharField(max_length=200)),
                ('bird', models.CharField(max_length=200)),
                ('room', models.CharField(max_length=200)),
                ('pastTenseVerb', models.CharField(max_length=200)),
                ('verb', models.CharField(max_length=200)),
                ('relative', models.CharField(max_length=200)),
                ('noun', models.CharField(max_length=200)),
                ('liquid', models.CharField(max_length=200)),
                ('verbWithIng', models.CharField(max_length=200)),
                ('bodyPart', models.CharField(max_length=200)),
                ('pluralNoun', models.CharField(max_length=200)),
                ('verbWithIngTwo', models.CharField(max_length=200)),
                ('nounTwo', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='game1',
        ),
    ]
