# Generated by Django 2.2 on 2022-03-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20220306_1129'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personOne', models.CharField(max_length=200)),
                ('personTwo', models.CharField(max_length=200)),
                ('verb', models.CharField(max_length=200)),
                ('noun', models.CharField(max_length=200)),
                ('nounTwo', models.CharField(max_length=200)),
                ('nounThree', models.CharField(max_length=200)),
                ('nounFour', models.CharField(max_length=200)),
            ],
        ),
    ]
