# Generated by Django 2.2 on 2022-03-06 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_gamethree'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyMember', models.CharField(max_length=200)),
                ('adjective', models.CharField(max_length=200)),
                ('adjectiveTwo', models.CharField(max_length=200)),
                ('activity', models.CharField(max_length=200)),
                ('activityTwo', models.CharField(max_length=200)),
                ('pluralNoun', models.CharField(max_length=200)),
                ('adjectiveThree', models.CharField(max_length=200)),
                ('noun', models.CharField(max_length=200)),
                ('nickName', models.CharField(max_length=200)),
            ],
        ),
    ]
