# Generated by Django 2.2 on 2022-03-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_gamefour'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('waterForm', models.CharField(max_length=200)),
                ('foodOne', models.CharField(max_length=200)),
                ('foodTwo', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
