# Generated by Django 2.2 on 2022-03-07 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_gamefive'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noun', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=200)),
                ('nounTwo', models.CharField(max_length=200)),
                ('verbWithIng', models.CharField(max_length=200)),
                ('clothing', models.CharField(max_length=200)),
                ('clothingTwo', models.CharField(max_length=200)),
                ('beverage', models.CharField(max_length=200)),
                ('food', models.CharField(max_length=200)),
            ],
        ),
    ]
