# Generated by Django 2.2 on 2022-03-07 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_gamesix'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSeven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=200)),
                ('adjective', models.CharField(max_length=200)),
                ('adjectiveTwo', models.CharField(max_length=200)),
                ('noun', models.CharField(max_length=200)),
                ('nounTwo', models.CharField(max_length=200)),
                ('adjectiveThree', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('verb', models.CharField(max_length=200)),
                ('verbTwo', models.CharField(max_length=200)),
                ('personTwo', models.CharField(max_length=200)),
                ('verbThree', models.CharField(max_length=200)),
                ('adjectiveFour', models.CharField(max_length=200)),
                ('verbFour', models.CharField(max_length=200)),
            ],
        ),
    ]
