# Generated by Django 2.2 on 2022-03-07 01:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_gameseven'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameseven',
            name='adjectiveFive',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
