# Generated by Django 2.2 on 2022-03-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_gameseven_adjectivefive'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holiday', models.CharField(max_length=200)),
                ('noun', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('costume', models.CharField(max_length=200)),
                ('adjective', models.CharField(max_length=200)),
                ('bodyPartPlural', models.CharField(max_length=200)),
                ('verb', models.CharField(max_length=200)),
                ('adjectiveTwo', models.CharField(max_length=200)),
                ('nounTwo', models.CharField(max_length=200)),
                ('food', models.CharField(max_length=200)),
                ('pluralNoun', models.CharField(max_length=200)),
            ],
        ),
    ]
