# Generated by Django 2.2 on 2022-03-07 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_gamenine_problemresolution'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properNoun', models.CharField(max_length=200)),
                ('verbWithIng', models.CharField(max_length=200)),
                ('noun', models.CharField(max_length=200)),
                ('pronoun', models.CharField(max_length=200)),
                ('nounTwo', models.CharField(max_length=200)),
                ('verb', models.CharField(max_length=200)),
            ],
        ),
    ]
