# Generated by Django 2.2 on 2022-03-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_gameten'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameEleven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verbWithIng', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=200)),
                ('verbWithIngTwo', models.CharField(max_length=200)),
                ('adjective', models.CharField(max_length=200)),
                ('adjectiveTwo', models.CharField(max_length=200)),
                ('personTwo', models.CharField(max_length=200)),
                ('verb', models.CharField(max_length=200)),
                ('adjectiveThree', models.CharField(max_length=200)),
                ('food', models.CharField(max_length=200)),
                ('clothing', models.CharField(max_length=200)),
                ('adjectiveFour', models.CharField(max_length=200)),
                ('adjectiveFive', models.CharField(max_length=200)),
            ],
        ),
    ]
