# Generated by Django 2.2 on 2022-03-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0016_gametwelve'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameThirteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container', models.CharField(max_length=200)),
                ('adjective', models.CharField(max_length=200)),
                ('adjectiveTwo', models.CharField(max_length=200)),
                ('noun', models.CharField(max_length=200)),
                ('animal', models.CharField(max_length=200)),
                ('vegetable', models.CharField(max_length=200)),
                ('vegetableTwo', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('adjectiveThree', models.CharField(max_length=200)),
            ],
        ),
    ]
