# Generated by Django 2.2 on 2022-03-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_gamethirteen'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFourteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dinosaurType', models.CharField(max_length=200)),
                ('noise', models.CharField(max_length=200)),
                ('animal', models.CharField(max_length=200)),
                ('bodyPart', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('smell', models.CharField(max_length=200)),
                ('number', models.IntegerField()),
                ('game', models.CharField(max_length=200)),
                ('emotion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='gamesix',
            name='number',
            field=models.IntegerField(),
        ),
    ]
