# Generated by Django 2.2 on 2022-03-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_auto_20220306_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameFifteen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=200)),
                ('ingredient', models.CharField(max_length=200)),
                ('adjective', models.CharField(max_length=200)),
                ('person', models.CharField(max_length=200)),
                ('adjectiveTwo', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('noun', models.CharField(max_length=200)),
                ('nounTwo', models.CharField(max_length=200)),
            ],
        ),
    ]
